services:
  # LGTM Stack - All in one container (Loki, Grafana, Tempo, Mimir)
  lgtm:
    image: docker.io/grafana/otel-lgtm:0.8.1
    ports:
      - "3002:3000"   # Grafana (khác với 3001)
      - "4321:4317"   # OTLP gRPC (khác với 4319)
      - "4322:4318"   # OTLP HTTP (khác với 4320)
    volumes:
      - ./lgtm/grafana:/data/grafana
      - ./lgtm/prometheus:/data/prometheus
      - ./lgtm/loki:/data/loki
    environment:
      - GF_PATHS_DATA=/data/grafana
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
